CREATE TABLE BOOK(
       Book_ID SERIAL PRIMARY KEY ,
	   Title VARCHAR(100) ,
	   Author VARCHAR(100),
	   Genre VARCHAR(50) ,
	   Published_year INT ,
	   Price NUMERIC(10,2) ,
	   Stock INT
);

CREATE TABLE customers(
     Customer_ID SERIAL PRIMARY KEY ,
	 Name VARCHAR(50), 
	 email VARCHAR(100),
	 phone VARCHAR(100),
	 city VARCHAR(50),
	 country VARCHAR(100)
);

CREATE TABLE ORDERS(
       	Order_id SERIAL PRIMARY KEY ,
		Customer_ID INT REFERENCES customers(Customer_ID),
		Book_ID INT REFERENCES BOOK(Book_ID),
		Order_date DATE,
		Quantity INT, 
		Total_Amount NUMERIC(10, 2)
);

SELECT * FROM BOOK ;

SELECT * FROM customers ;

SELECT * FROM ORDERS ;

-- 1 RETERIVE ALL THE BOOKS IN THE 'FICTION' GENRE 
SELECT * FROM BOOK
WHERE genre = 'Fiction' ;

--2 FINDS BOOK PUBLISHED AFTER THE YEAR 1950
SELECT * FROM BOOK
WHERE (published_year) > 1950 ;

--3 LIST ALL THE CUSTOMERS FROM THE CANADA
SELECT * FROM customers
WHERE country = 'Canada' ;

--4 SHOW ORDERS PLACED IN NOVEMEBER 2025
SELECT * FROM ORDERS
WHERE order_date BETWEEN '2023-11-01' AND '2023-11-30' ;

--5 RETERIVE THE TOTEL STOCKS OF BOOKS AVAILABLE
SELECT SUM(stock) AS_TOTAL_STOCK
FROM BOOK ;

--6 FINDS THE DETAILS OF MOST EXPENSIVE BOOKS
SELECT * FROM BOOK
ORDER BY price DESC LIMIT 1 ;

--7 SHOW ALL THE CUSTOMERS WHO ORDERED MORE THAN 1 QUANTITY BOOK 
SELECT * FROM ORDERS
WHERE quantity > 1;

-- 8 RETERIEVE ALL THE ORDERS WHERE THE TOTAL AMOUNT EXCEEDS $20
SELECT * FROM ORDERS
WHERE total_amount > 20;

--9 LIST ALL THE GENRES AVAILABLE IN THE BOOK TABLE 
SELECT DISTINCT genre FROM BOOK;

--10 FIND THE BOOKS WITH THE LOWEST STOCK 
SELECT * FROM BOOK 
ORDER BY stock ASC LIMIT 5;

--11 CALCULATE THE TOTAL REVENUE GENERATED FROM ALL ORDERS 
SELECT SUM(total_amount) AS REVENUE
FROM ORDERS ;



-- ADVANCED QUES 

--1 RETERIEVE THE TOTAL NUMBER OF BOOKS SOLD FOR EACH GENRE
SELECT b.genre, SUM(o.quantity) AS TOTAL_BOOK_SOLD
FROM ORDERS o
JOIN BOOK b 
ON b.book_id = o.book_id 
GROUP BY genre ;

--2 FIND THE AVERAGE PRICE OF BOOKS IN THE 'FANTASY' GENRE
SELECT AVG(price) as avg_price
FROM BOOK
WHERE genre = 'Fantasy' ;

--3 LIST ALL THE CUSTOMERS WHO PLACED AT LEAST 2 ORDERS 
SELECT o.customer_id, c.name, COUNT(o.order_id) AS TOTAL_ORDER
FROM ORDERS o
JOIN customers c
ON c.customer_id = o.customer_id 
GROUP BY o.customer_id , c.name
HAVING COUNT(o.order_id) >= 2;

--4 FIND THE MOST FREQUENTLY ORDERED BOOK
SELECT o.book_id, b.title, COUNT(o.order_id) AS ORDER_COUNT
FROM ORDERS o
JOIN book b
ON b.book_id = o.book_id
GROUP BY o.book_id, b.title
ORDER BY ORDER_COUNT DESC LIMIT 1;

--5 SHOW THE TOP 3 MOST EXPENSIVE BOOKS OF 'FANTASY' GENRE 
SELECT * FROM BOOK 
ORDER BY price DESC LIMIT 3;

--6 RETERIEVE THE TOTAL QUANTITY OF BOOKS SOLD BY EACH AUTHOR 
SELECT b.author, SUM(o.quantity) AS TOTAL_QUANTITY
FROM ORDERS o
JOIN BOOK b 
ON b.book_id = o.book_id 
GROUP BY b.author ;

--7 LIST THE CITIES WHERE CUSTOMERS WHO SPENT OVER $30 ARE LOCATED 
SELECT DISTINCT c.city, o.total_amount 
FROM ORDERS o
JOIN customers c 
ON c.customer_id = o.customer_id
WHERE o.total_amount > 30 ;

-- 8 FIND THE CUSTOMERS WHO SPENT MOST ON THE ORDERS 
SELECT c.name, c.customer_id, SUM(o.total_amount) AS TOTAL_SPENT
FROM ORDERS o
JOIN customers c
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name
ORDER BY TOTAL_SPENT DESC LIMIT 5 ;

--9 CALCULATE THE STOCK REMAINING AFTER THE FULFILLING ALL ORDERS 
SELECT b.book_id, b.stock, COALESCE(SUM(quantity), 0) AS ORDER_QUANTITY,
b.stock - COALESCE(SUM(quantity), 0) AS REMAINING_STOCK
FROM BOOK b 
LEFT JOIN ORDERS o
ON b.book_id = o.book_id
GROUP BY b.book_id 
ORDER BY book_id ;
